/**
 * Reports Page — Real-time Financial & Academic Reports
 * Generates actual data-driven reports with CSV export + print support
 */

import { useState, useRef } from "react";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  BarChart3,
  Download,
  Printer,
  Loader2,
  DollarSign,
  TrendingUp,
  TrendingDown,
  FileSpreadsheet,
  Receipt,
  Users,
  GraduationCap,
  Calendar,
  ArrowLeft,
  RefreshCcw,
  Package,
} from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { toast } from "sonner";

const API_BASE =
  import.meta.env.VITE_API_BASE_URL || "http://localhost:5000";

function formatCurrency(n: number) {
  return `PKR ${n.toLocaleString()}`;
}

function formatDate(d: string | Date) {
  return new Date(d).toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

// CSV Export Helper
function downloadCSV(filename: string, headers: string[], rows: string[][]) {
  const csv = [
    headers.join(","),
    ...rows.map((r) =>
      r.map((c) => `"${String(c ?? "").replace(/"/g, '""')}"`).join(","),
    ),
  ].join("\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${filename}-${new Date().toISOString().slice(0, 10)}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

// Print Helper
function printContent(title: string, el: HTMLDivElement | null) {
  if (!el) return;
  const win = window.open("", "_blank");
  if (!win) return;
  win.document.write(`
    <html><head><title>${title}</title>
    <style>
      body{font-family:Arial,sans-serif;padding:30px;color:#1a1a1a}
      h1{font-size:22px;margin-bottom:4px}
      h2{font-size:16px;margin:20px 0 8px;border-bottom:2px solid #e5e7eb;padding-bottom:4px}
      .meta{color:#6b7280;font-size:12px;margin-bottom:20px}
      .kpi-row{display:flex;gap:20px;margin:16px 0}
      .kpi{flex:1;border:1px solid #e5e7eb;border-radius:8px;padding:16px}
      .kpi .label{font-size:12px;color:#6b7280}.kpi .value{font-size:20px;font-weight:700;margin-top:4px}
      .green{color:#059669}.red{color:#dc2626}.blue{color:#2563eb}
      table{width:100%;border-collapse:collapse;margin-top:8px}
      th,td{text-align:left;padding:8px 12px;border-bottom:1px solid #e5e7eb;font-size:13px}
      th{background:#f9fafb;font-weight:600}
      .right{text-align:right}
      .footer{margin-top:30px;font-size:11px;color:#9ca3af;border-top:1px solid #e5e7eb;padding-top:12px}
    </style></head><body>
    ${el.innerHTML}
    <div class="footer">Generated by Edwardian Academy ERP &mdash; ${new Date().toLocaleString()}</div>
    </body></html>
  `);
  win.document.close();
  win.print();
}

// ═══════════════════════════════════════════════════════
// FINANCIAL REPORT VIEW
// ═══════════════════════════════════════════════════════
function FinancialReport({ period, onBack }: { period: string; onBack: () => void }) {
  const printRef = useRef<HTMLDivElement>(null);

  const { data, isLoading, refetch } = useQuery({
    queryKey: ["report", "financial", period],
    queryFn: async () => {
      const res = await fetch(
        `${API_BASE}/api/finance/generate-report?period=${period}`,
        { credentials: "include" },
      );
      if (!res.ok) throw new Error("Failed to generate report");
      return res.json();
    },
  });

  const report = data?.data;

  const handleCSV = () => {
    if (!report) return;
    const headers = ["Category", "Type", "Amount (PKR)", "Transactions"];
    const rows = [
      ...(report.revenueByCategory || []).map((r: any) => [r.category, "Revenue", String(r.amount), String(r.transactions)]),
      ...(report.expenseByCategory || []).map((e: any) => [e.category, "Expense", String(e.amount), String(e.transactions)]),
      ["", "", "", ""],
      ["Total Revenue", "", String(report.totalRevenue), ""],
      ["Total Expenses", "", String(report.totalExpenses), ""],
      ["Net Profit", "", String(report.netProfit), ""],
      ["Fees Collected", "", String(report.feesCollected?.total || 0), String(report.feesCollected?.count || 0)],
    ];
    downloadCSV(`financial-report-${period}`, headers, rows);
    toast.success("CSV downloaded");
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-24">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
        <span className="ml-3 text-muted-foreground">Generating report...</span>
      </div>
    );
  }

  if (!report) {
    return (
      <div className="text-center py-16 text-muted-foreground">
        Failed to generate report.{" "}
        <Button variant="link" onClick={() => refetch()}>Retry</Button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <Button variant="ghost" onClick={onBack}><ArrowLeft className="mr-2 h-4 w-4" /> Back to Reports</Button>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" onClick={() => refetch()}><RefreshCcw className="mr-1.5 h-4 w-4" /> Refresh</Button>
          <Button variant="outline" size="sm" onClick={handleCSV}><FileSpreadsheet className="mr-1.5 h-4 w-4" /> Export CSV</Button>
          <Button size="sm" onClick={() => printContent("Financial Report", printRef.current)}><Printer className="mr-1.5 h-4 w-4" /> Print / Save PDF</Button>
        </div>
      </div>

      <div ref={printRef}>
        <h1 style={{ fontSize: 22, fontWeight: 700, marginBottom: 2 }}>Edwardian Academy — {report.period} Financial Report</h1>
        <p className="meta" style={{ color: "#6b7280", fontSize: 13, marginBottom: 20 }}>Generated on {formatDate(report.generatedAt)}</p>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <Card className="border-l-4 border-emerald-500"><CardContent className="pt-5 pb-4"><p className="text-sm text-muted-foreground">Total Revenue</p><p className="text-2xl font-bold text-emerald-700 mt-1">{formatCurrency(report.totalRevenue)}</p></CardContent></Card>
          <Card className="border-l-4 border-red-500"><CardContent className="pt-5 pb-4"><p className="text-sm text-muted-foreground">Total Expenses</p><p className="text-2xl font-bold text-red-600 mt-1">{formatCurrency(report.totalExpenses)}</p></CardContent></Card>
          <Card className="border-l-4 border-blue-500"><CardContent className="pt-5 pb-4"><p className="text-sm text-muted-foreground">Net Profit</p><p className={`text-2xl font-bold mt-1 ${report.netProfit >= 0 ? "text-emerald-700" : "text-red-600"}`}>{formatCurrency(report.netProfit)}</p></CardContent></Card>
          <Card className="border-l-4 border-amber-500"><CardContent className="pt-5 pb-4"><p className="text-sm text-muted-foreground">Fees Collected</p><p className="text-2xl font-bold text-amber-700 mt-1">{formatCurrency(report.feesCollected?.total || 0)}</p><p className="text-xs text-muted-foreground mt-1">{report.feesCollected?.count || 0} payments</p></CardContent></Card>
        </div>

        {report.revenueByCategory?.length > 0 && (
          <Card className="mt-6">
            <CardHeader><CardTitle className="flex items-center gap-2 text-lg"><TrendingUp className="h-5 w-5 text-emerald-600" />Revenue Breakdown</CardTitle></CardHeader>
            <CardContent>
              <Table>
                <TableHeader><TableRow><TableHead>Category</TableHead><TableHead className="text-center">Transactions</TableHead><TableHead className="text-right">Amount</TableHead></TableRow></TableHeader>
                <TableBody>
                  {report.revenueByCategory.map((r: any) => (<TableRow key={r.category}><TableCell className="font-medium">{r.category}</TableCell><TableCell className="text-center"><Badge variant="outline">{r.transactions}</Badge></TableCell><TableCell className="text-right font-bold text-emerald-700">{formatCurrency(r.amount)}</TableCell></TableRow>))}
                  <TableRow className="bg-emerald-50"><TableCell className="font-bold">Total</TableCell><TableCell /><TableCell className="text-right font-bold text-emerald-800">{formatCurrency(report.totalRevenue)}</TableCell></TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        )}

        {report.expenseByCategory?.length > 0 && (
          <Card className="mt-6">
            <CardHeader><CardTitle className="flex items-center gap-2 text-lg"><TrendingDown className="h-5 w-5 text-red-600" />Expense Breakdown</CardTitle></CardHeader>
            <CardContent>
              <Table>
                <TableHeader><TableRow><TableHead>Category</TableHead><TableHead className="text-center">Transactions</TableHead><TableHead className="text-right">Amount</TableHead></TableRow></TableHeader>
                <TableBody>
                  {report.expenseByCategory.map((e: any) => (<TableRow key={e.category}><TableCell className="font-medium">{e.category}</TableCell><TableCell className="text-center"><Badge variant="outline">{e.transactions}</Badge></TableCell><TableCell className="text-right font-bold text-red-600">{formatCurrency(e.amount)}</TableCell></TableRow>))}
                  <TableRow className="bg-red-50"><TableCell className="font-bold">Total</TableCell><TableCell /><TableCell className="text-right font-bold text-red-700">{formatCurrency(report.totalExpenses)}</TableCell></TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        )}

        {report.revenueByCategory?.length === 0 && report.expenseByCategory?.length === 0 && (
          <Card className="mt-6"><CardContent className="py-12 text-center text-muted-foreground"><Receipt className="h-10 w-10 mx-auto mb-3 opacity-30" /><p className="font-medium">No transactions found for this period</p><p className="text-sm mt-1">Try selecting a wider date range.</p></CardContent></Card>
        )}
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════
// TEACHER PAYMENT REPORT
// ═══════════════════════════════════════════════════════
function TeacherPaymentReport({ onBack }: { onBack: () => void }) {
  const printRef = useRef<HTMLDivElement>(null);

  const { data, isLoading } = useQuery({
    queryKey: ["report", "teachers"],
    queryFn: async () => {
      const res = await fetch(`${API_BASE}/api/teachers`, { credentials: "include" });
      if (!res.ok) throw new Error("Failed to load teachers");
      return res.json();
    },
  });

  const teachers = data?.data || [];
  const totalBalance = teachers.reduce((s: number, t: any) => s + (t.walletBalance || 0), 0);
  const totalCredited = teachers.reduce((s: number, t: any) => s + (t.totalCredited || 0), 0);
  const totalDebited = teachers.reduce((s: number, t: any) => s + (t.totalDebited || 0), 0);

  const handleCSV = () => {
    const headers = ["Teacher ID", "Name", "Subject", "Status", "Wallet Balance", "Total Credited", "Total Debited"];
    const rows = teachers.map((t: any) => [t.teacherId || "", t.name || "", t.subject || "", t.status || "", String(t.walletBalance ?? 0), String(t.totalCredited ?? 0), String(t.totalDebited ?? 0)]);
    downloadCSV("teacher-payment-report", headers, rows);
    toast.success("CSV downloaded");
  };

  if (isLoading) return <div className="flex items-center justify-center py-24"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div>;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <Button variant="ghost" onClick={onBack}><ArrowLeft className="mr-2 h-4 w-4" /> Back</Button>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={handleCSV}><FileSpreadsheet className="mr-1.5 h-4 w-4" /> CSV</Button>
          <Button size="sm" onClick={() => printContent("Teacher Payment Report", printRef.current)}><Printer className="mr-1.5 h-4 w-4" /> Print</Button>
        </div>
      </div>
      <div ref={printRef}>
        <h1 style={{ fontSize: 22, fontWeight: 700, marginBottom: 2 }}>Edwardian Academy — Teacher Payment Report</h1>
        <p className="meta" style={{ color: "#6b7280", fontSize: 13, marginBottom: 20 }}>Generated on {formatDate(new Date())}</p>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
          <Card className="border-l-4 border-emerald-500"><CardContent className="pt-5 pb-4"><p className="text-sm text-muted-foreground">Total Credited</p><p className="text-xl font-bold text-emerald-700 mt-1">{formatCurrency(totalCredited)}</p></CardContent></Card>
          <Card className="border-l-4 border-red-500"><CardContent className="pt-5 pb-4"><p className="text-sm text-muted-foreground">Total Paid Out</p><p className="text-xl font-bold text-red-600 mt-1">{formatCurrency(totalDebited)}</p></CardContent></Card>
          <Card className="border-l-4 border-amber-500"><CardContent className="pt-5 pb-4"><p className="text-sm text-muted-foreground">Outstanding Balance</p><p className="text-xl font-bold text-amber-700 mt-1">{formatCurrency(totalBalance)}</p></CardContent></Card>
        </div>

        <Card><CardContent className="p-0">
          <Table>
            <TableHeader><TableRow><TableHead>ID</TableHead><TableHead>Name</TableHead><TableHead>Subject</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Credited</TableHead><TableHead className="text-right">Paid</TableHead><TableHead className="text-right">Balance</TableHead></TableRow></TableHeader>
            <TableBody>
              {teachers.length === 0 ? (
                <TableRow><TableCell colSpan={7} className="text-center py-8 text-muted-foreground">No teachers found</TableCell></TableRow>
              ) : teachers.map((t: any) => (
                <TableRow key={t._id}>
                  <TableCell className="font-mono text-xs">{t.teacherId}</TableCell>
                  <TableCell className="font-medium">{t.name}</TableCell>
                  <TableCell>{t.subject || "—"}</TableCell>
                  <TableCell><Badge variant={t.status === "active" ? "default" : "secondary"}>{t.status}</Badge></TableCell>
                  <TableCell className="text-right text-emerald-700 font-medium">{formatCurrency(t.totalCredited || 0)}</TableCell>
                  <TableCell className="text-right text-red-600 font-medium">{formatCurrency(t.totalDebited || 0)}</TableCell>
                  <TableCell className="text-right font-bold">{formatCurrency(t.walletBalance || 0)}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent></Card>
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════
// STUDENT REPORT
// ═══════════════════════════════════════════════════════
function StudentReport({ onBack }: { onBack: () => void }) {
  const printRef = useRef<HTMLDivElement>(null);

  const { data, isLoading } = useQuery({
    queryKey: ["report", "students"],
    queryFn: async () => {
      const res = await fetch(`${API_BASE}/api/students`, { credentials: "include" });
      if (!res.ok) throw new Error("Failed");
      return res.json();
    },
  });

  const students = data?.data || [];
  const totalStudents = students.length;
  const activeStudents = students.filter((s: any) => s.status === "active" || s.status === "Active").length;
  const totalMonthlyFee = students.reduce((s: number, st: any) => s + (st.feeAmount || st.monthlyFee || 0), 0);

  const handleCSV = () => {
    const headers = ["Student ID", "Name", "Father", "Class", "Status", "Monthly Fee", "Contact"];
    const rows = students.map((s: any) => [s.studentId || "", s.studentName || s.name || "", s.fatherName || "", s.class || s.className || "", s.status || "", String(s.feeAmount || s.monthlyFee || 0), s.phone || s.contactNumber || ""]);
    downloadCSV("student-report", headers, rows);
    toast.success("CSV downloaded");
  };

  if (isLoading) return <div className="flex items-center justify-center py-24"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div>;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <Button variant="ghost" onClick={onBack}><ArrowLeft className="mr-2 h-4 w-4" /> Back</Button>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={handleCSV}><FileSpreadsheet className="mr-1.5 h-4 w-4" /> CSV</Button>
          <Button size="sm" onClick={() => printContent("Student Report", printRef.current)}><Printer className="mr-1.5 h-4 w-4" /> Print</Button>
        </div>
      </div>
      <div ref={printRef}>
        <h1 style={{ fontSize: 22, fontWeight: 700, marginBottom: 2 }}>Edwardian Academy — Student Report</h1>
        <p className="meta" style={{ color: "#6b7280", fontSize: 13, marginBottom: 20 }}>Generated on {formatDate(new Date())} &bull; Total: {totalStudents} students</p>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
          <Card className="border-l-4 border-violet-500"><CardContent className="pt-5 pb-4"><p className="text-sm text-muted-foreground">Total Students</p><p className="text-2xl font-bold text-violet-700">{totalStudents}</p></CardContent></Card>
          <Card className="border-l-4 border-emerald-500"><CardContent className="pt-5 pb-4"><p className="text-sm text-muted-foreground">Active Students</p><p className="text-2xl font-bold text-emerald-700">{activeStudents}</p></CardContent></Card>
          <Card className="border-l-4 border-amber-500"><CardContent className="pt-5 pb-4"><p className="text-sm text-muted-foreground">Expected Monthly Fee</p><p className="text-2xl font-bold text-amber-700">{formatCurrency(totalMonthlyFee)}</p></CardContent></Card>
        </div>

        <Card><CardContent className="p-0"><div className="max-h-[500px] overflow-auto">
          <Table>
            <TableHeader><TableRow><TableHead>ID</TableHead><TableHead>Name</TableHead><TableHead>Father</TableHead><TableHead>Class</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Monthly Fee</TableHead></TableRow></TableHeader>
            <TableBody>
              {students.map((s: any) => (
                <TableRow key={s._id}>
                  <TableCell className="font-mono text-xs">{s.studentId}</TableCell>
                  <TableCell className="font-medium">{s.studentName || s.name}</TableCell>
                  <TableCell>{s.fatherName || "—"}</TableCell>
                  <TableCell>{s.class || s.className || "—"}</TableCell>
                  <TableCell><Badge variant={s.status === "active" || s.status === "Active" ? "default" : "secondary"}>{s.status}</Badge></TableCell>
                  <TableCell className="text-right font-medium">{formatCurrency(s.feeAmount || s.monthlyFee || 0)}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div></CardContent></Card>
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════
// EXPENSE REPORT
// ═══════════════════════════════════════════════════════
function ExpenseReport({ onBack }: { onBack: () => void }) {
  const printRef = useRef<HTMLDivElement>(null);

  const { data, isLoading } = useQuery({
    queryKey: ["report", "expenses"],
    queryFn: async () => {
      const res = await fetch(`${API_BASE}/api/expenses`, { credentials: "include" });
      if (!res.ok) throw new Error("Failed");
      return res.json();
    },
  });

  const expenses = data?.data || [];
  const totalExpenses = expenses.reduce((s: number, e: any) => s + (e.amount || 0), 0);
  const byCategory: Record<string, { total: number; count: number }> = {};
  expenses.forEach((e: any) => {
    const cat = e.category || "Uncategorized";
    if (!byCategory[cat]) byCategory[cat] = { total: 0, count: 0 };
    byCategory[cat].total += e.amount || 0;
    byCategory[cat].count++;
  });

  const handleCSV = () => {
    const headers = ["Date", "Category", "Title", "Vendor", "Amount (PKR)", "Recorded By"];
    const rows = expenses.map((e: any) => [formatDate(e.expenseDate || e.createdAt), e.category || "", e.title || "", e.vendorName || "", String(e.amount || 0), e.paidBy?.fullName || "System"]);
    downloadCSV("expense-report", headers, rows);
    toast.success("CSV downloaded");
  };

  if (isLoading) return <div className="flex items-center justify-center py-24"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div>;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <Button variant="ghost" onClick={onBack}><ArrowLeft className="mr-2 h-4 w-4" /> Back</Button>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={handleCSV}><FileSpreadsheet className="mr-1.5 h-4 w-4" /> CSV</Button>
          <Button size="sm" onClick={() => printContent("Expense Report", printRef.current)}><Printer className="mr-1.5 h-4 w-4" /> Print</Button>
        </div>
      </div>
      <div ref={printRef}>
        <h1 style={{ fontSize: 22, fontWeight: 700, marginBottom: 2 }}>Edwardian Academy — Expense Report</h1>
        <p className="meta" style={{ color: "#6b7280", fontSize: 13, marginBottom: 20 }}>{expenses.length} expenses totaling {formatCurrency(totalExpenses)}</p>

        <h2 style={{ fontSize: 16, fontWeight: 600, marginBottom: 8 }}>Category Summary</h2>
        <Card className="mb-6"><CardContent className="p-0">
          <Table>
            <TableHeader><TableRow><TableHead>Category</TableHead><TableHead className="text-center">Count</TableHead><TableHead className="text-right">Total</TableHead></TableRow></TableHeader>
            <TableBody>
              {Object.entries(byCategory).sort((a, b) => b[1].total - a[1].total).map(([cat, info]) => (
                <TableRow key={cat}><TableCell className="font-medium">{cat}</TableCell><TableCell className="text-center"><Badge variant="outline">{info.count}</Badge></TableCell><TableCell className="text-right font-bold text-red-600">{formatCurrency(info.total)}</TableCell></TableRow>
              ))}
              <TableRow className="bg-red-50"><TableCell className="font-bold">Grand Total</TableCell><TableCell className="text-center font-bold">{expenses.length}</TableCell><TableCell className="text-right font-bold text-red-700">{formatCurrency(totalExpenses)}</TableCell></TableRow>
            </TableBody>
          </Table>
        </CardContent></Card>

        <h2 style={{ fontSize: 16, fontWeight: 600, marginBottom: 8 }}>All Expenses</h2>
        <Card><CardContent className="p-0"><div className="max-h-[400px] overflow-auto">
          <Table>
            <TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Category</TableHead><TableHead>Title</TableHead><TableHead>Vendor</TableHead><TableHead className="text-right">Amount</TableHead></TableRow></TableHeader>
            <TableBody>
              {expenses.map((e: any) => (
                <TableRow key={e._id}>
                  <TableCell className="text-sm text-muted-foreground">{formatDate(e.expenseDate || e.createdAt)}</TableCell>
                  <TableCell><Badge variant="outline">{e.category}</Badge></TableCell>
                  <TableCell className="font-medium">{e.title || "—"}</TableCell>
                  <TableCell>{e.vendorName || "—"}</TableCell>
                  <TableCell className="text-right font-bold text-red-600">{formatCurrency(e.amount)}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div></CardContent></Card>
      </div>
    </div>
  );
}

// ═══════════════════════════════════════════════════════
// MAIN REPORTS PAGE
// ═══════════════════════════════════════════════════════
type ActiveReport = null | "financial" | "teachers" | "students" | "expenses";

export default function Reports() {
  const [activeReport, setActiveReport] = useState<ActiveReport>(null);
  const [financePeriod, setFinancePeriod] = useState("month");
  const [showPeriodPicker, setShowPeriodPicker] = useState(false);

  if (activeReport === "financial") return <DashboardLayout title="Financial Report"><FinancialReport period={financePeriod} onBack={() => setActiveReport(null)} /></DashboardLayout>;
  if (activeReport === "teachers") return <DashboardLayout title="Teacher Payment Report"><TeacherPaymentReport onBack={() => setActiveReport(null)} /></DashboardLayout>;
  if (activeReport === "students") return <DashboardLayout title="Student Report"><StudentReport onBack={() => setActiveReport(null)} /></DashboardLayout>;
  if (activeReport === "expenses") return <DashboardLayout title="Expense Report"><ExpenseReport onBack={() => setActiveReport(null)} /></DashboardLayout>;

  const reportCards = [
    { title: "Financial Report", description: "Revenue vs expenses breakdown by category with net profit, CSV export, and printable format", icon: DollarSign, color: "text-emerald-600", bgColor: "bg-emerald-100", action: () => setShowPeriodPicker(true) },
    { title: "Teacher Payment Report", description: "All teacher salaries, wallet credits, payouts, and outstanding balances", icon: GraduationCap, color: "text-blue-600", bgColor: "bg-blue-100", action: () => setActiveReport("teachers") },
    { title: "Expense Report", description: "Complete expense log with category breakdown and vendor details", icon: Receipt, color: "text-red-600", bgColor: "bg-red-100", action: () => setActiveReport("expenses") },
    { title: "Student Report", description: "Enrollment stats, fee amounts, class distribution, and contact info", icon: Users, color: "text-violet-600", bgColor: "bg-violet-100", action: () => setActiveReport("students") },
    { title: "Attendance Report", description: "Student gate scan attendance analytics — view in Gate Scanner", icon: Calendar, color: "text-amber-600", bgColor: "bg-amber-100", action: () => { window.location.href = "/gatekeeper"; } },
    { title: "Asset Registry Report", description: "Investment assets, depreciation tracking, and current valuations", icon: Package, color: "text-teal-600", bgColor: "bg-teal-100", action: () => { window.location.href = "/finance?tab=assets"; } },
  ];

  return (
    <DashboardLayout title="Reports">
      <div className="space-y-6">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2">
            <BarChart3 className="h-6 w-6 text-primary" />
            Reports & Analytics
          </h1>
          <p className="text-muted-foreground">Generate real data-driven reports with CSV export and print support</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {reportCards.map((card) => (
            <Card key={card.title} className="hover:shadow-lg transition-shadow cursor-pointer group" onClick={card.action}>
              <CardHeader>
                <div className="flex items-center gap-4">
                  <div className={`p-3 rounded-lg ${card.bgColor} group-hover:scale-110 transition-transform`}>
                    <card.icon className={`h-6 w-6 ${card.color}`} />
                  </div>
                  <CardTitle className="text-lg">{card.title}</CardTitle>
                </div>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground text-sm mb-4">{card.description}</p>
                <Button variant="outline" size="sm" className="w-full gap-2"><Download className="h-4 w-4" />Generate Report</Button>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>

      <Dialog open={showPeriodPicker} onOpenChange={setShowPeriodPicker}>
        <DialogContent className="sm:max-w-sm">
          <DialogHeader><DialogTitle>Select Report Period</DialogTitle></DialogHeader>
          <div className="space-y-4 py-4">
            <Select value={financePeriod} onValueChange={setFinancePeriod}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="today">Today</SelectItem>
                <SelectItem value="week">This Week</SelectItem>
                <SelectItem value="month">This Month</SelectItem>
                <SelectItem value="full">All Time</SelectItem>
              </SelectContent>
            </Select>
            <Button className="w-full" onClick={() => { setShowPeriodPicker(false); setActiveReport("financial"); }}><BarChart3 className="mr-2 h-4 w-4" />Generate Report</Button>
          </div>
        </DialogContent>
      </Dialog>
    </DashboardLayout>
  );
}